name: Publish app to Releases

on:
  push:
    tags:
      - 'v*' 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: dotnet build --configuration Release
      
    - name: Get app version
      id: version
      run: echo "::set-env name=VERSION::$(cat version.txt)"


    - name: Publish Release
      id: publish_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        RELEASE_VERSION: ${{ env.VERSION }}
      with:
        tag_name: |
          v${{ env.VERSION }}
          debug
        release_name: Release v${{ env.VERSION }}
        draft: false
        prerelease: true

    - name: Upload Artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      with:
        upload_url: ${{ steps.publish_release.outputs.upload_url }}
        asset_path: ./bin/Debug/net6.0-windows/OpusTool.exe
        asset_name: OpusTool.exe
        asset_content_type: application/octet-stream
