name: Publish app to Releases

on:
  push:
    paths:
      - 'version.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Get app version
        run: |
          version=$(cat version.txt)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --configuration Release /p:AssemblyVersion=${{ env.VERSION }}

      - name: Publish app 
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --output publish 

      - name: Zip executable
        run: zip -j ./publish/OpusTool.zip ./publish/OpusTool.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: true

      - name: Upload Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/OpusTool.zip
          asset_name: OpusTool.zip
          asset_content_type: application/zip
